### ISSUE TITLE
Broken output html

### ISSUE THREAD

**Issue by luebken** [theonewolf/TermRecord#18]
Hi 

I'm on a Mac and installed with brew. Not sure wether #17 is related.

I run a simple `TermRecord -o test.html` with the output:
``` 
Script done, output file is /var/folders/87/xx79l6td4z5_ftr9l49b3t1h0000gn/T/tmpOTadtW
``` 

Unfortunately the resulting `test.html` doesn't work. I get an error in Chrome console: `Uncaught TypeError: Cannot read property '1' of undefined test.html:120`

It seems that the data array is missing. When looking at other examples I am missing the whole `<script>` tag.

**Comment by sm11963** [comment]
Any fix for this? I have the same issue.

**Comment by sedusa** [comment]
Just wanted to find out if anyone had solved the issue.

![screen shot 2015-01-14 at 7 03 17 pm](https://cloud.githubusercontent.com/assets/5447546/5750248/09cbe908-9c20-11e4-997c-d5062f95d544.png)

**Comment by jmhobbs** [comment]
It seems that maybe TermRecord isn't finding ttyrec?
If I explicitly call that as the backend, my recording works fine.

```bash
$ TermRecord -o test.html -b ttyrec
```

Mac OSX 10.10.2

**Comment by theonewolf** [comment]
As soon as I can test the fix, I'll push out a new version of TermRecord.  Sorry this took so long guys!  And thanks for @jmhobbs for stepping in :smile:

**Comment by theonewolf** [comment]
This looks fixed, still need to double-check, pushing a new release to PyPI.
